In [ ]:
# Can represet images as this (3x5 image)
# We wouldn't store an image in memory as a list as would take up too much storage in memory and slow things down
[[123,12,143,12,44],[1,14,182,4,98],[1,1,1,1,1]]
# Numpy solves this

In [2]:
import numpy
n = numpy.arange(27) # numpy n-dimensional array

In [5]:
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [4]:
type(n)

numpy.ndarray

In [7]:
# We can convert prior array into 2 dimensional
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [8]:
# Three dimensional array
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [11]:
# Can make a numpy array from a python list
m = numpy.asarray([[123,12,143,12,44],[1,14,182,4,98],[1,1,1,1,1]])
m

array([[123,  12, 143,  12,  44],
       [  1,  14, 182,   4,  98],
       [  1,   1,   1,   1,   1]])