In [4]:
import numpy
n = numpy.arange(27) # numpy n-dimensional array

In [5]:
type(n)

numpy.ndarray

In [6]:
# Three dimensional array
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [7]:
# Can make a numpy array from a python list
m = numpy.asarray([[123,12,143,12,44],[1,14,182,4,98],[1,1,1,1,1]])
m

array([[123,  12, 143,  12,  44],
       [  1,  14, 182,   4,  98],
       [  1,   1,   1,   1,   1]])

In [9]:
import cv2

In [11]:
# Second argument - 0 means grayscale, 1 means in RGB
im_g = cv2.imread("./files/smallgray.png",0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [12]:
im_rgb = cv2.imread("./files/smallgray.png",1)
im_rgb # Output is the RGB values

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [13]:
# To write images from numbers
# Name and then the numpy array
cv2.imwrite("./files/newsmallgray.png", im_g)

True